### ISSUE TITLE
[PE-D][Tester C] Missing implementation of feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#197] opened 2024-11-08 20:02 UTC
![image.png](https://raw.githubusercontent.com/nigellqx/ped/main/files/2422161c-571a-4897-9e06-736f3647b56a.png)
The feature of customizing the app's theme is missing

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nigellqx/ped#10

**Comment by anselmlong** [comment] 2024-11-09 11:14
Duplicate of #192

**Closed as completed by anselmlong** 2024-11-09 11:14 UTC
