### ISSUE TITLE
[PE-D][Tester B] Same issue as #8

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#188] opened 2024-11-08 18:36 UTC
![image.png](https://raw.githubusercontent.com/OrangeCatLoves/ped/main/files/2f73d153-8fa5-4141-bbef-18fad6ebc8ce.png)

For the "..." with regards to the email part this time.

Ran this command => :add -n TestNaMe -p 98765432 -e TestAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAA@gmail.com -l 510999 -t FRIEND -r RemarkTest

The argument for -e part is an exaggeration, more emphasis on the length and the fact that there's no limits placed on the length the email can accept which can affect the Ui. Imagine having so many long data and seeing so many trailing "..." at the back for most contacts - not very pleasant for the Ui.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: OrangeCatLoves/ped#9

**Comment by anselmlong** [comment] 2024-11-09 11:08
Duplicate of #164

**Closed as completed by anselmlong** 2024-11-09 11:08 UTC
